### ISSUE TITLE
[DEV] - Plans for 0.1.0

### ISSUE THREAD

**Issue by TomDonoghue** [spiketools/spiketools#10]
Sometimes soonish, we can make an initial `0.1.0` release with an initial alpha version of the module. This issue collects things to do for this initial release. 

Code updates (functionality):
- [x] general plot updates (done in #79)
- [x] add the start of the `sims` sub-module (done in #21)
- [x] figure out a plan for the objects (in progress in #19)

Module updates:
- [x] finish an initial test suite (done in #34)
- [x] add doctests to (some) functions (done in #30)
- [x] do a sweep for organization & name consistency
  - [x] for example, having `spiketools/spatial/` and `spiketools/plts/space` is inconsistent
  - [x] we mix between the terms "firing rate" and "spike rate"
- [x] fix up some module conventions (overview in #13)
  - [x] standardize units & approaches (in progress in #11 & #12)

Documentation updates:
- [x] fix up the glossary page, including a sweep for consistent terminology (#119)
- [x] fix up README, including defining scope, etc
- [x] draft some initial tutorials (#32)

**Comment by TomDonoghue** [comment]
Calling this done!!
