### ISSUE TITLE
[MNT] - Add doctest examples

### ISSUE THREAD

**Issue by TomDonoghue** [spiketools/spiketools#30]
Goal - add doctest examples across the module

Files to add doctests to (check off when PR's are merged):
- [x] `spiketools/measures/measures` (Claire) - #40 
- [x] `spiketools/measures/conversions` (Claire) - #70  
- [x]  `spiketools/utils/spikes` (Claire) - #69  
- [x] `spiketools/spatial/information` (Sandra) - #42 
- [x] `spiketools/spatial/occupancy` (Sandra) - #26, #27, #35, #36
- [x] `spiketools/spatial/position` (Sandra) - #41
- [x] `spiketools/sims/prob` (Sandra) - #55
- [x] `spiketools/sims/dist` (Claire) - #71 

#### Doctest Examples

For examples of doctests, check the NeuroDSP module (https://github.com/neurodsp-tools/neurodsp). Note that one of the goals of doctests is to write in this `Example` section, that gets rendered on the documentation website. 

For example,
- InCode: https://github.com/neurodsp-tools/neurodsp/blob/main/neurodsp/sim/periodic.py#L43
- InDocs: https://neurodsp-tools.github.io/neurodsp/generated/neurodsp.sim.sim_oscillation.html
- Examples that simulate example data: https://github.com/neurodsp-tools/neurodsp/blob/main/neurodsp/spectral/power.py

#### Doctest Goals

The goal of doctests is to provide a minimal example of running the function. 

In terms of scope, typically we want:
- a _very_ simplified version of running the function
- first, write a plain text sentence explaining the 
- if there are multiple "ways" to use the function, then there can be multiple different examples
- keep each example specific to this function (generally, not adding subsequent processing / plotting, etc)

#### Doctest HowTos

Technical notes on doctests:
- and code after `>>>` will get run by doctests
- anything written right after a code line is the expected output
- if you want to set a doctest line to _not_ run, add `# doctest:+SKIP` at the end of the line
- the tests that run when you open a PR will now check the doctests

#### Running Doctests

Once you have pytest installed, you can check doctests locally by doing:
```
# Move into the 'spiketools' folder '~/spiketools/spiketools` (eg. `cd `spiketools`)
# Run doctests, ignoring the tests folder
pytest --doctest-modules --ignore=tests
```
OR
```
# Run this command from the base repository ('~/spiketools/)
pytest --doctest-modules --ignore=spiketools/tests spiketools
```
