### ISSUE TITLE
[DOC] - Make tutorials

### ISSUE THREAD

**Issue by TomDonoghue** [spiketools/spiketools#32]
We should make tutorial pages for each of our core modules.

Tutorials to create:
- [x] measures (Claire) added in #81 
- [x] spatial (Sandra) added in #74
- [x] stats (Sandra) added in #77 
- [x] simulations (Claire) added in #88 

Development suggestions:
- Initial files, with something of a layout, are already made in the `tutorials` folder 
- When writing tutorials, I usually work in a Jupyter notebook, testing things
    - You can then copy elements into the tutorial file
- In general, we will use simulated data to show each thing (some basic simulation code has been added)
- Make a separate PR for each topic / tutorial

Note: tutorial pages are something we will workshop and edit a bunch. Start with drafts, hitting any of the main points you think we should hit. It's fine to leave template sections (like: "do X here", or "describe Y here"). Based on the early drafts we can organize what to look further into, and how to edit these 

### Examples

Examples from NeuroDSP:
- Source: https://github.com/neurodsp-tools/neurodsp/tree/fd3adde3a35831ad18c883c563d722fceb687cf7/tutorials
- Website: https://neurodsp-tools.github.io/neurodsp/auto_tutorials/index.html

### Documentation Approach

Links to documentation tools we are using:
- Sphinx: https://www.sphinx-doc.org/en/master/
- Sphinx-Gallery: https://sphinx-gallery.github.io/stable/index.html
