### ISSUE TITLE
[MNT] - Add unit tests

### ISSUE THREAD

**Issue by TomDonoghue** [spiketools/spiketools#34]
Functions that need unit-tests adding:
- [x] spiketools/spatial/occupancy - compute_bin_time (Sandra) - #44 
- [x] spiketools/spatial/occupancy - compute_occupancy (Sandra) - #45 
- [x] spiketools/spatial/information - compute_spatial_information_2d (Sandra) #47
- [x] spiketools/spatial/information - compute_spatial_information_1d (Sandra) #48
- [x] spiketools/spatial/information - compute_spatial_information (Sandra) #53
- [x] spiketools/sims/prob - sim_spiketrain_prob (Sandra) #72 
- [x] spiketools/sims/dist - sim_spiketrain_binom (Sandra) #73 
- [x] spiketools/sims/dist - sim_spiketrain_poisson (Sandra) #62
- [x] spiketools/sims/utils - refractory (Claire) #68
