### ISSUE TITLE
Plot tweaks / updates

### ISSUE THREAD

**Issue by TomDonoghue** [spiketools/spiketools#84]
Plot helpers / utilities:
- [x] add a helper function for initializing subplot axes (done in #87)
- [x] add a basic `plot_line(s)` plot to `plts/data` (done in #86 ) 
- [x] add annotate funcs, including `_add_vline` and `_add_shade` (done in #89)
- [x] add a basic `plot_dots` plot to `plts/data`

Plot edits:
- [x] `plot_rasters`: update to take a shade region (done in #89)
- [x] `plot_positions`: update to allow for trial-by-trial input (done in #100)
- [x] `plot_positions`: update to visualize extra landmarks, etc

Naming consistency:
- [x] 'shade' is currently used (across plots) to refer to error shading and avlines. Maybe make more consistent?
- [x] 'times' is currently used inconsistently between `plot_waveform` and `plot_waveform3d`

**Comment by TomDonoghue** [comment]
The core things here are done in #114, so i'm going to close this here now
